#
# @Author: Jxtopher
# @Date: 2020-01-07
# @Purpose: Travis !
# @copyright CC-BY-NC-SA
# @see : https://devhints.io/travis
#
#########################
# project configuration #
#########################
language: cpp
dist: bionic

ignore:
  - docs/*
  - configuration/*
  - instances/*
  - interface-python/*

before_install:
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq libcppunit-dev libjsoncpp-dev libjsoncpp1 libboost-log-dev libboost-program-options-dev libboost-iostreams-dev libmongoclient-dev libmongoclient0 g++-8  doxygen
  - travis_retry sudo apt-get install -qq libargtable2-dev libmicrohttpd-dev libjsoncpp-dev libhiredis-dev

script:
  - sudo rm /usr/bin/g++
  - sudo ln -s /usr/bin/g++-8 /usr/bin/g++
  - cd build
  - cmake ..
  - make
  - ./stocos-unittest
