#########################
# project configuration #
#########################
language: cpp

dist: trusty
#sudo: required
#group: edge

###################
# global settings #
###################
before_install:
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq libjsoncpp-dev libjsoncpp1 libboost-all-dev libmongoclient-dev libmongoclient0

################
# build matrix #
################

matrix:
  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-8

################
# build script #
################

script:
  - cd build
  - cmake .. 
  - make
