#########################
# project configuration #
#########################
language: cpp

dist: bionic  #trusty
#sudo: required
#group: edge

###################
# global settings #
###################
before_install:
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq libjsoncpp-dev libjsoncpp1 libboost-all-dev libmongoclient-dev libmongoclient0 g++-8

################
# build matrix #
################

matrix:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

################
# build script #
################

script:
  - cd /tmp
  - git clone git://github.com/cinemast/libjson-rpc-cpp.git
  - mkdir -p libjson-rpc-cpp/build
  - cd libjson-rpc-cpp/build
  - cmake .. && make
  - sudo make install
  - sudo ldconfig
  - sudo rm /usr/bin/g++
  - sudo ln -s /usr/bin/g++-8 /usr/bin/g++
  - cd build
  - cmake .. 
  - make
