version: 2.1
jobs:
  build:
    docker:
      - image: debian:buster
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: >
            apt-get update && apt-get install -y
            build-essential
            cmake
            pkg-config
            libpcre3-dev 
            zlib1g-dev
            libicu-dev
            python
            libcppunit-dev
            libjsoncpp-dev
            libjsoncpp1
            openmpi-bin
            libboost-iostreams-dev
            libboost-program-options-dev
            libboost-log-dev
            libc6
            libc6-dev
            libmongoclient-dev 
            ibmongoclient0
            doxygen
            git
            
      - run: 
          name: make
          command: cmake .. && make
          working_directory: ~/project/build
