version: 2.1
jobs:
  build:
    docker:
      - image: debian:buster
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: >
            apt-get update && apt-get install -y
            clang-format
            cppcheck
            build-essential
            cmake
            doxygen
            git
            libargtable2-dev
            libboost-iostreams-dev
            libboost-log-dev
            libboost-program-options-dev
            libc6
            libc6-dev
            libcppunit-dev
            libcurl4
            libcurl4-gnutls-dev
            libhiredis-dev
            libicu-dev
            libjsoncpp-dev
            libjsoncpp1
            libmicrohttpd-dev
            libmongoclient-dev
            libmongoclient0
            libpcre3-dev
            pkg-config
            python3.7
            python3-pip
            zlib1g-dev
      - run:
          name: Install Dependencies python3.7
          command: >
            python3.7 -m pip install numpy argparse
      - run:
          name: Compilation of the project
          command: cmake .. && make -j 1
          working_directory: ~/project/build
      - run:
          name: Tests
          command: make test ARGS="-V"
          working_directory: ~/project/build
